import PDFDocument from "pdfkit";

/**
 * Generates a simple salary PDF buffer.
 * Keep clean and professional (no emojis).
 */
export function makeSalaryPdf({ title, worker, periodLabel, rows, totals }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 40 });
      const chunks = [];
      doc.on("data", (d) => chunks.push(d));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      doc.fontSize(18).text(title, { align: "left" });
      doc.moveDown(0.5);

      doc.fontSize(11).text(`Worker: ${worker.name} (${worker.workerId})`);
      doc.text(`Trade: ${worker.trade}`);
      doc.text(`Phone: ${worker.phone || "-"}`);
      doc.text(`Period: ${periodLabel}`);
      doc.moveDown(1);

      doc.fontSize(12).text("Breakdown", { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(10);
      rows.forEach((r) => {
        doc.text(`${r.label}: ${r.value}`);
      });

      doc.moveDown(1);
      doc.fontSize(12).text("Totals", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(`Base Approved Pay: ${totals.baseApproved.toFixed(2)} SAR`);
      doc.text(`OT Approved Pay: ${totals.otApproved.toFixed(2)} SAR`);
      doc.text(`Leave Deductions: ${totals.leaveDeductions.toFixed(2)} SAR`);
      doc.moveDown(0.3);
      doc.fontSize(12).text(`Net Payable: ${totals.net.toFixed(2)} SAR`);

      doc.moveDown(2);
      doc.fontSize(9).text("Generated by FASTEP WORK", { align: "left" });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}
